### ISSUE TITLE
Feedback on Hews2

### ISSUE THREAD

**Issue by daegalus** [leavjenn/Hews2#1]
I am a huge fan of Hews and when Hews2 was announced, I installed it right away. But there are a few experience issues that are less than ideal. I figure I would list them here, and just let you adjust them as you see fit:

- Using the in-app browser with the custom chrome has weird issues sometimes. Mostly with http->https redirects. It doesn't seem to do them and then I get a Android system error about it not being supported.

![Screenshot_20220928-122840](https://user-images.githubusercontent.com/670212/192872123-87ffc6d9-82ec-4da0-affc-0b5c57d00c5f.png)

- Disabling the in-app browser in favor of the system browser just gives me a chrome-less view that has no buttons for going back or doing anything. In Hews1 it would use my default browsers view and the chrome would be handled there. Seems like a minor regression?

![Screenshot_20220928-122926](https://user-images.githubusercontent.com/670212/192872189-6450c7f8-ac88-434b-9441-a1bf07ba2548.png)

- There really isn't a theme that matches the less busy look of Hews1. I spent about an hour flipping back and forth between Hews1 and Hews2 to get the look similar. Maybe offer a Theme/Style that matches Hews1 colors and layout closer? I do like the Dark and Sepia colors of Hews1 more.

![Screenshot_20220928-122756](https://user-images.githubusercontent.com/670212/192872247-570d01ff-ac97-48ee-9a74-361375015535.png)
![Screenshot_20220928-122809](https://user-images.githubusercontent.com/670212/192872270-672dfbc8-9bec-42f8-91f9-059adb70ba56.png)

Other than this, Hews2 is great!

**Comment by chaosphinx** [comment]
This has been fixed now. Thanks for your feedback.

**Comment by leavjenn** [comment]
The non-https websites bug has been fixed now. About the theme thing... I'll consider how to smooth the migration from v2 to v1. Thanks for your feedback.
