### ISSUE TITLE
Login no longer working

### ISSUE THREAD

**Issue by xingped** [leavjenn/Hews2#3]
Hi, I sent an email via the app, but hopefully posting this here will also be seen. It appears that as of a few days ago, the Login functionality has stopped working. It signs in correctly and redirects back to the sign in view on the app with a toast notification saying sign in successful, but it doesn't act like I signed in (still see sign in buttons, profile not logged in). Hope someone sees this!

**Comment by crontab-pw** [comment]
I'm having the same issue as well. When I log in, the app shows a successful notification but fails to actually log me in. 

![Screenshot_20240225_091239.jpg](https://github.com/leavjenn/Hews2/assets/120604713/3e42d921-29bc-4604-aa02-3a43b79b0c8b)

**Comment by leavjenn** [comment]
@crontab-pw Hi, does your username contain capital letters? I think there is a bug with this situation.

**Comment by crontab-pw** [comment]
> @crontab-pw Hi, does your username contain capital letters? I think there is a bug with this situation.

The username I am using has small letters, followed by an underscore followed by numbers. Without divulging my username, I have some examples of the type of format it is in:

john_316
larry_2222
kelly_12345

Maybe the underscore is causing the issue?

**Comment by leavjenn** [comment]
@xingped @crontab-pw I think I got what happened. Your accounts' "about" section is empty. Hews 2 fetches user info via`https://hn.algolia.com/api/v1/users/{your_username}`. If the "about" section is empty, this API returns null, and app doesn't handle this correctly. Will fix it in next release, thanks for your feedback.

**Comment by crontab-pw** [comment]
@leavjenn 

After updating the app with the Feb 28 login bug fix, I was able to successfully log in. Thank you.

**Comment by leavjenn** [comment]
Fixed in version 0.2.0.
